#ifndef PINS_DEFINES_HPP
#define PINS_DEFINES_HPP

// ADC0 as ADC input
#define PWM_OUT_PORT PORTB
#define PWM_OUT_DDR DDRB
#define PWM_OUT_POS PB1
#define PWM_OUT_NEG PB2
#define DYNAMIC_MODE_PORT PORTC
#define DYNAMIC_MODE_PIN_REG PINC
#define DYNAMIC_MODE_PIN PC5

#endif  // PINS_DEFINES_HPP